name: erentacar_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter_secure_storage: ^10.3.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.2
  table_calendar: ^3.2.0
  flutter_rating_bar: ^4.0.1
  signalr_netcore: ^1.4.4
  flutter_stripe: ^13.0.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
